const userData = {
  name: "Nico De Castro",
  role: "Software & Data Engineering",
  avatarUrl: "/avatar.png",
  address: "Laguna, Philippines",
  projects: [
  {
    title: "LOLCODE Interpreter",
    liveLink: "",
    codeLink: "https://github.com/nicodecastro/lolcode-interpreter",
    imgUrl: "/projects/lolcode.png",
    imgAlt: "LOLCODE Interpreter card",
    description: "Developed an interpreter for the LOLCODE programming language using Python 3, implementing lexical analysis, parsing, and execution for core language features. Built a custom graphical user interface using customtkinter, allowing users to write and run LOLCODE programs interactively.",
    technologies: ["Python", "CustomTkinter"],
  },
  {
    title: "Elbi Donation System",
    liveLink: "",
    codeLink: "https://github.com/nicodecastro/Elbi-Donation-System",
    imgUrl: "/projects/elbidonation.png",
    imgAlt: "Elbi Donation System card",
    description: "Built a mobile donation app connecting donors and organizations, with Firebase Authentication for secure login, role-based access, Firebase Firestore for real-time data, and Firebase Storage for image handling. Added SMS and push notifications via Telephony and Firebase Cloud Messaging.",
    technologies: ["Flutter", "Firebase", "Telephony"],
  },
  {
    title: "AgriConnect",
    liveLink: "",
    codeLink: "https://github.com/nicodecastro/AgriConnect",
    imgUrl: "/projects/agriconnect.png",
    imgAlt: "Agriconnect E-commerce Web App card",
    description: "Led the project management and contributed full-stack development for an academic e-commerce web app project connecting farmers and consumers through a farm-to-table initiative. Managed a team of four, overseeing the planning and execution to ensure timely and successful completion.",
    technologies: ["React", "Express", "MongoDB", "NodeJS", "REST API"],
  },
  {
    title: "FoodUP",
    liveLink: "",
    codeLink: "https://github.com/nicodecastro/FoodUP",
    imgUrl: "/projects/foodup.png",
    imgAlt: "FoodUP Review App card",
    description: "Developed a food and restaurant review application as an academic project using Python, Tkinter GUI and MariaDB database. Designed and implemented complex database queries and schema and contributed full-stack development.",
    technologies: ["Python", "MariaDB", "Tkinter"],
  },
  {
    title: "A Mage's Return",
    liveLink: "",
    codeLink: "https://github.com/nicodecastro/A-Mages-Return",
    imgUrl: "/projects/amagesreturn.png",
    imgAlt: "A Mage's Return Game card",
    description: "A Java-based shooter game developed using the JavaFX library. An academic mini-project to practice the design and application of OOP concepts—Abstraction, Encapsulation, Inheritance, and Polymorphism—in a working project.",
    technologies: ["Java", "JavaFX", "OOP"],
  },
  {
    title: "Generic Solvers App",
    liveLink: "https://okkinn.shinyapps.io/CMSC150Project/",
    codeLink: "https://github.com/nicodecastro/Generic-Solvers-App",
    imgUrl: "/projects/genericsolversapp.png",
    imgAlt: "Generic Solvers Web App",
    description: "Developed an R application for an academic project that provides generic solvers for quadratic spline interpolation and polynomial regression, and a simplex implementation for the diet optimization problem. It consists of a shiny app deployed using shinyApp.",
    technologies: ["R", "Shiny", "ShinyApps"],
  },
],
experience: [
  {
    type: "Work",
    title: "Part-Time Java Tutor",
    company: "Freelance",
    year: "SEPT 2026 — PRESENT",
    desc: [
      "Provide one-on-one Java programming instruction covering object-oriented programming, data structures, algorithms, debugging, and software development fundamentals.",
      "Design hands-on coding exercises and guide students through debugging and problem solving, adapting instruction to their skill level and learning needs.",
    ],
    technologies: ["Java", "Object-Oriented Programming", "Data Structures", "Algorithms"],
  },
  {
    type: "Work",
    title: "Freelance Software Engineer",
    company: "Freelance",
    year: "DEC 2025 — MAR 2026",
    desc: [
      "Developed Python-based data extraction workflows for a ~100 GB Microsoft SQL Server database containing 35+ tables and 200M+ combined rows, producing multiple CSV files for machine-learning use cases.",
      "Implemented chunked and streamed processing in Python to reduce memory usage and improve runtime and reliability on low-compute client devices.",
      "Implemented a research-based vulnerability-prioritization model as three Axonius queries across 12 departments, and contributed to dashboard design and automated email reporting.",
    ],
    technologies: ["Python", "Microsoft SQL Server", "Axonius", "CSV"],
  },
  {
    type: "Work",
    title: "Software Developer Intern",
    company: "Datalogic Systems Corporation",
    year: "JUN 2025 — JULY 2025",
    desc: [
      "Built backend services and four REST endpoints using Laravel and Microsoft SQL Server against an existing read-only production database, supporting an internal monitoring dashboard for development and support requests, employee status, meetings, and deadlines.",
      "Built a separate Laravel application with CRUD operations across 4–5 entities, exposing authenticated REST APIs with API-key protection for controlled read-write access to SQL Server data.",
      "Developed a Python Windows service using watchdog to continuously detect newly generated payslip files, match recipients through SQL Server, and automate email delivery from an existing legacy payroll workflow.",
    ],
    technologies: ["Laravel", "Microsoft SQL Server", "REST APIs", "Python", "Windows Service"],
  },
  {
    type: "Leadership",
    title: "Co-Captain",
    company: "UPLB Men's Volleyball Team",
    year: "AUG 2024 — PRESENT",
    desc: [
      "Led and motivated a team of 20 players, fostering a culture of accountability and discipline.",
      "Planned and executed semestral team-building sessions, improving performance and collaboration among the team.",
      "Raised funds to support team expenses by organizing and supervising multiple fundraising volleyball tournaments.",
    ],
    skills: ["Team Leadership", "Event Management"]
  },
  {
    type: "Leadership",
    title: "Finance Co-Head",
    company: "Kappa Phi Sigma Conservation and Development Society ",
    year: "NOV 2023 — JAN 2024",
    desc: [
      "Led financial planning and reporting for the Kappanalig 2024 outreach program.",
      "Co-led a team of six in fundraising activities that raised 20,000 pesos through donations, sponsorships, and events.",
      "The funds supported 55 children with essential goods.",
    ],
    skills: ["Team Leadership", "Project Management", "Organizational Skills", "Analytical Skills", "Data-Driven Decision Making"],
  },
  ],
  socialLinks: {
    linkedin: "https://www.linkedin.com/in/nicodecastro/",
    github: "https://github.com/nicodecastro",
  },
};

export default userData;