const userData = {
  name: "Nico De Castro",
  designation: "Laguna, Philippines 📍",
  avatarUrl: "/avatar.png",
  address: "Santa Rosa City, Laguna, Philippines",
  projects: [
  {
    title: "LOLCODE Interpreter",
    liveLink: "",
    codeLink: "https://github.com/nicodecastro/lolcode-interpreter",
    imgUrl: "/projects/lolcode.png",
    imgAlt: "LOLCODE Interpreter card",
    description: "Developed an interpreter for the LOLCODE programming language using Python 3, implementing lexical analysis, parsing, and execution for core language features. Built a custom graphical user interface using customtkinter, allowing users to write and run LOLCODE programs interactively.",
    technologies: ["Python", "CustomTkinter"],
  },
  {
    title: "Elbi Donation System",
    liveLink: "",
    codeLink: "https://github.com/nicodecastro/Elbi-Donation-System",
    imgUrl: "/projects/elbidonation.png",
    imgAlt: "Elbi Donation System card",
    description: "Built a mobile donation app connecting donors and organizations, with Firebase Authentication for secure login, role-based access, Firebase Firestore for real-time data, and Firebase Storage for image handling. Added SMS and push notifications via Telephony and Firebase Cloud Messaging.",
    technologies: ["Flutter", "Firebase", "Telephony"],
  },
  {
    title: "AgriConnect",
    liveLink: "",
    codeLink: "https://github.com/nicodecastro/AgriConnect",
    imgUrl: "/projects/agriconnect.png",
    imgAlt: "Agriconnect E-commerce Web App card",
    description: "Led the project management and contributed full-stack development for an academic e-commerce web app project connecting farmers and consumers through a farm-to-table initiative. Managed a team of four, overseeing the planning and execution to ensure timely and successful completion.",
    technologies: ["React", "Express", "MongoDB", "NodeJS", "REST API"],
  },
  {
    title: "FoodUP",
    liveLink: "",
    codeLink: "https://github.com/nicodecastro/FoodUP",
    imgUrl: "/projects/foodup.png",
    imgAlt: "FoodUP Review App card",
    description: "Developed a food and restaurant review application as an academic project using Python, Tkinter GUI and MariaDB database. Designed and implemented complex database queries and schema and contributed full-stack development.",
    technologies: ["Python", "MariaDB", "Tkinter"],
  },
  {
    title: "A Mage's Return",
    liveLink: "",
    codeLink: "https://github.com/nicodecastro/A-Mages-Return",
    imgUrl: "/projects/amagesreturn.png",
    imgAlt: "A Mage's Return Game card",
    description: "A Java-based shooter game developed using the JavaFX library. An academic mini-project to practice the design and application of OOP concepts—Abstraction, Encapsulation, Inheritance, and Polymorphism—in a working project.",
    technologies: ["Java", "JavaFX", "OOP"],
  },
  {
    title: "Generic Solvers App",
    liveLink: "https://okkinn.shinyapps.io/CMSC150Project/",
    codeLink: "https://github.com/nicodecastro/Generic-Solvers-App",
    imgUrl: "/projects/genericsolversapp.png",
    imgAlt: "Generic Solvers Web App",
    description: "Developed an R application for an academic project that provides generic solvers for quadratic spline interpolation and polynomial regression, and a simplex implementation for the diet optimization problem. It consists of a shiny app deployed using shinyApp.",
    technologies: ["R", "Shiny", "ShinyApps"],
  },
],
experience: [
  {
    title: "Software Developer Intern",
    company: "Datalogic Systems Corporation",
    year: "JUN 2025 — JULY 2025",
    desc: "Deployed an internal monitoring dashboard using Laravel, React, and SQL Server, improving UI, data flow, and performance. Built a standalone CRUD Laravel application with secure RESTful APIs and maintained documentation to streamline onboarding. Created a Python-based Windows service automating the secure emailing of payslips using SQL Server.",
  },
  {
    title: "Co-Captain",
    company: "UPLB Men's Volleyball Team",
    year: "AUG 2024 — PRESENT",
    desc: "Led and motivated a team of 20 players, fostering a culture of accountability and discipline. Planned and executed semestral team-building sessions, improving performance and collaboration among the team. Successfully raised funds to support team expenses by organizing and supervising multiple fundraising volleyball tournaments.",
    skills: ["Team Leadership", "Event Management"]
  },
  {
    title: "Finance Co-Head",
    company: "Kappa Phi Sigma Conservation and Development Society ",
    year: "NOV 2023 — JAN 2024",
    desc: "Led financial planning for the Kappanalig 2024 outreach program. Managed transparent financial reporting. Co-led a team of 6 in successful fundraising activities. Efforts resulted in raising 20,000 pesos through donations, sponsorships, and events, benefiting 55 children with essential goods.",
    skills: ["Team Leadership", "Project Management", "Organizational Skills", "Analytical Skills", "Data-Driven Decision Making"],
  },
  ],
  socialLinks: {
    twitter: "https://x.com/dcstnic",
    linkedin: "https://www.linkedin.com/in/nicodecastro/",
    github: "https://github.com/nicodecastro",
  },
};

export default userData;